### PR TITLE
Use ObsPreviewImage for photo gallery and use PhotoCount component

### PR DESCRIPTION
**Pull request by Chrischuck**
#482 

- [x] circular checkbox in top-end (selected controls checked state) with shadow (this might need to be its own component like CircularCheckbox or something; hoping it can be rendered with CSS and the existing checkmark icon)
- [x] <PhotoCount /> in bottom-end

Screenshot 2023-03-11 at 8 06 53 PM

### CODE REVIEW

**Review by jtklein — CHANGES_REQUESTED** [review]
Placements are all fine from what I can see. However, on Android there is a very small space in the selection marker. When ticked, between the circle outline and the circle in the center with the checkmark. Let me know if you want to add it here or make a separate issue.

**Comment by Chrischuck** [comment]
@jtklein what device are you using? would you be able to point it out in the pictures on the pr comment?

**Comment by jtklein** [comment]
This is a screenshot from the emulator on my machine. But I can also see it on my physical device. I think I can even see it in your screenshot zoomed in. It looks to be like a 1 Pixel mismatch on my emulator.
Screenshot 2023-03-13 at 16 27 49

**Comment by Chrischuck** [comment]
@jtklein ohh i didnt even see that, good eye. i'll give that a fix!

**Comment by Chrischuck** [comment]
@jtklein looks like it's [this](https://github.com/facebook/react-native/issues/33060) issue. Went ahead and pushed a fix

**Pull request merged**
