### PR TITLE
fix: photocount text overflows icon

### LINKED ISSUE #2131: PhotoCount text overflows icon
Happening when system font is set to the largest size, probably everywhere PhotoCount gets used but particularly on obs grid items and ObsDetails. If possible we should try and scale up the icon along with the text size, but failing that we should probably just not allow that text to scale up.

IMG_675790649A5A-1 IMG_F6F3347FD7BD-1

### PR DESCRIPTION
**Pull request by israr002**
closes #2131

### CODE REVIEW

**Review by kueda — CHANGES_REQUESTED** [review]
You've got a test snapshot you need to update, but more importantly this still isn't looking very good at the largest sizes:

Screenshot 2024-10-16 at 6 06 45 PM

The scaling of the photo count icon probably needs to be limited, and we need to try and make sure the text is always inside the white square part of the icon.

**Comment by israr002** [comment]
@kueda I have tested the photo count on the observation screen, and it's working fine on my device. Could you please share the steps you followed to generate the scenario you encountered?

https://github.com/user-attachments/assets/3497b558-c4ae-4d8f-b41a-80dedf0fb85f

**Comment by kueda** [comment]
@israr002 you need to run the app in iOS and set the font size to the maximum allowed size. You might be able to achieve something similar in Android at the max size, but since we're not yet supporting Android, it's most important that this work in iOS at the moment.

**Comment by angielt** [comment]
Might have to check with @abhasinat again if this issue is still needed. While I was working on #2257, he mentioned to set the maxFontSizeMultiplier for the PhotoCount number to 1.

**Comment by kueda** [comment]
@israr002 are you still planning to work on this?

**Comment by israr002** [comment]
Yes I am working on this

**Review by kueda — APPROVED** [review]

**Pull request merged**
