### PR TITLE
Fix unclickable observations bug (#298)

### PR DESCRIPTION
**Pull request by Chrischuck**
Fixes issue #298 and #339 

Ended up translating the entire list rather than just the header.

### CODE REVIEW

**Review by kueda — CHANGES_REQUESTED** [review]
This fixes the relevant issues on iOS for me, but on Android the app crashes after sign in while loading My Observations. There's no stack trace, and the most useful info in logcat is this:

```
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'terminating with uncaught exception of type facebook::jni::JniException: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available'
```

Can you replicate, and either way, any idea what's going on?

**Comment by Chrischuck** [comment]
@kueda  i'm getting that issue even on the main branch. did a clean build and everything...guessing it's a deeper issue but i havent had much time to debug. will take a look later today or tomorrow

**Comment by kueda** [comment]
Seems to have occurred in 516b1a487ddc140288eb5a7b35cb52e23b0f1027. I'm spending some time on it today, but holler if you have any ideas.

**Comment by Chrischuck** [comment]
@kueda I got lucky and was able to get an error message. Pushed the fix along in this pr.

Screenshot 2023-01-10 at 2 24 50 PM

**Comment by kueda** [comment]
Hm, we've been hitting different problems with the `capitalize` function in `DisplayTaxonName`, which probably has to do with unicode handling in Hermes for Android. Replacing the long unicode string at https://github.com/inaturalist/iNaturalistReactNative/blob/main/src/components/DisplayTaxonName.js#L46 with a blank string fixes the problem, so we might have to disable that weird capitalization code for now. We're experimenting with it and may just push a fix to main.

**Comment by Chrischuck** [comment]
Sounds good to me, appreciate the help on this one

**Review by kueda — APPROVED** [review]

**Comment by kueda** [comment]
Ok, the Android issue should be fixed in #347, and yeah, definitely unrelated to this work, so I think this is good to go.

**Pull request merged**
