### PR TITLE
Fix for issues #918 and #993.

### PR DESCRIPTION
**Pull request by joergmlpts**

### CODE REVIEW

**Review by kueda — CHANGES_REQUESTED** [review]
This introduces a different bug:

1. Follow the repro steps in #993; no more endless spinner, which is great
2. Save the observation
3. On MyObservations, the observation row now shows no photo, even though it does show a photo count indicator of 2
4. Tap on the observation
5. You get this error
    ```
    TypeError: Cannot read property 'toJSON' of null

    This error is located at:
        in PhotoDisplayContainer (created by ObsDetails)
        in RCTScrollContentView (created by ScrollView)
        in RCTScrollView (created by ScrollView)
        in ScrollView (created by ScrollView)
        in ScrollView
        in NativeWind.ScrollView
        in NativeWind.NoName
        in Unknown (created by ObsDetails)
        in RCTSafeAreaView
        in Styled
        in NativeWind.NoName
        in Unknown (created by ObsDetails)
        in ObsDetails (created by ObsDetailsContainer)
        in ObsDetailsContainer (created by SceneView)
    ```

**Comment by joergmlpts** [comment]
That appears to happen here:

```
        // TODO replace this hack. Without this you get errors about the
        // photo objects being invalidated down in PhotoScroll, but the
        // questions remains, why are these objects getting invalidated in
        // the first place? We are not deleting them, so what's happening
        // to them and why?
        op => (
          op.photo.toJSON
            ? op.photo.toJSON( )
            : op.photo
        )
      )
```

**Comment by joergmlpts** [comment]
Sorry for wasting your time.

Another attempt at a fix is coming soon.

**Comment by budowski** [comment]
@joergmlpts - hint at what's causing the crash - that's because `toJSON` is a Realm object function (it's probably expecting an `ObservationPhoto` instance or similar), and instead it's getting a regular JS object

**Comment by joergmlpts** [comment]
@budowski The crash in the original code happens because `updatedObs.observationPhotos` cannot be modified outside of a write transaction when `updatedObs` is the same object as `currentObservation` and `currentObservation` is a Realm object.

My illfated fix correctly used the JSON of `currentObservation` as `updatedObs` and thus it could modify `updatedObs.observationPhotos` - the drash was gone. It did not work properly because `currentObservationPhotos` was still obtained from the Realm object and that containted `photo` as a Realm object which downstream turned into `null`.

The new fix also uses the JSON of `currentObservation` as `updatedObs` but it obtains `updatedObs.observationPhotos` from this JSON object. Hence the issues downstream are gone. The type check is optional, the change also works when toJSON() is called for json object. I wanted to avoid a function call that might be a deep copy of an observation when it is not necessary.

**Pull request closed without merging**
