### PR TITLE
ObsDetail : DQA

### PR DESCRIPTION
**Pull request by angielt**
PR includes the Data Quality Assessment. I used various strings to represent the different test indicators(checkmark and warning icons) and checking the data for each of them. Probably is a better method of checking them thats more readable and less repetitive that i'm not aware of at the moment.

### CODE REVIEW

**Review by kueda — CHANGES_REQUESTED** [review]
Mostly working really well so far. Here's a first pass at functionality bugs:

- [ ] "Date specified" has a green check when viewing the DQA of an observation with no date
- [ ] "Location specified" has a green check when viewing the DQA of an observation with no location
- [ ] "Has Photos or Sounds" has a green check when viewing the DQA of an observation with no media
- [ ] "Can the Community Taxon still be improved?" allows you to vote yes but not no, and it does not show whether you voted or the number of votes.

**Comment by angielt** [comment]
What is the date that is preferred to be used to check for observation date on DQA?  I can't seem to make an observation with no date since all observations have a created_at date

**Comment by kueda** [comment]
observed_on. Try making an obs on the website and viewing it in the app.

**Comment by kueda** [comment]
> For the "Can the Community Taxon still be improved?" I thought we were waiting for the v2 version of the endpoint.

Forgot about that. Please add some indicator that it's TODO, though, like `<PlaceholderText text="TODO" />`. That we we all know it's not broken, just not done yet.

**Review by kueda — APPROVED** [review]
Nothing blocking, mostly just stylistic feedback.

**Pull request merged**
